services:
  api:
    build: ./services/api
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - frontend

  worker:
    build: ./services/worker
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_NAME=${POSTGRES_DB}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=jobs-postgres
    depends_on:
      jobs-postgres:
        condition: service_healthy
    networks:
      - backend
      - frontend

  auth-service:
    build: ./services/auth
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_USER=${POSTGRES_USER_FOR_AUTH}
      - DB_NAME=${POSTGRES_DB_FOR_AUTH}
      - DB_PASSWORD=${POSTGRES_PASSWORD_FOR_AUTH}
      - DB_HOST=users-postgres
    depends_on:
      users-postgres:
        condition: service_healthy
    networks:
      - backend
      - frontend

  jobs-postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - data:/var/lib/postgresql/data

  users-postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER_FOR_AUTH}
      - POSTGRES_DB=${POSTGRES_DB_FOR_AUTH}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_FOR_AUTH}
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB_FOR_AUTH} -U ${POSTGRES_USER_FOR_AUTH}"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - users:/var/lib/postgresql/data

volumes:
  data:
  users:

networks:
  frontend:
  backend: