FROM golang:1.26.4-alpine AS builder
WORKDIR /services/worker
COPY go.mod .
RUN go mod download
COPY . .
RUN go build -o app

FROM gcr.io/distroless/static-debian12
WORKDIR /services/worker
COPY --from=builder /services/worker/app app
CMD [ "./app" ]